version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t myapp .
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 8080:8080 --name myapp_container myapp
            sleep 5 # Wait for the container to start
            apt install curl
            curl -sSf http://localhost:8080 # Test if the application responds
            docker stop myapp_container # Stop the container
            docker rm myapp_container # Remove the container
