version: 2.1

jobs:
  build:
    machine: # executor type
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t myapp .
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 8080:8080 --name myapp_container myapp
            sleep 5 # Wait for the container to start
            wget http://localhost:8080
            docker stop myapp_container
            docker rm myapp_container
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag myapp $DOCKER_USERNAME/myapp
            docker push $DOCKER_USERNAME/myapp
