version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t myapp .
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 8080:8080 --name myapp_container myapp
            sleep 5 # Wait for the container to start
            curl -sSf http://localhost:3000 # Test if the application responds
            docker stop myapp_container # Stop the container
            docker rm myapp_container # Remove the container
